from django import forms
from .models import LeaderBoard
from django.core.exceptions import ValidationError

class save_leaderBoard(forms.Form):

    
    username = forms.CharField(label='What is your Name or Username?', widget=forms.TextInput(attrs={'placeholder': 'Add your Username or Name.'}), required=True)
    comment = forms.CharField(
        label='Add a comment! (optional)',
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Write a comment.'})
    )


    COUNTRIES_LIST = [
        ('None', '-- Select a Country --'),
        ('af', 'Afghanistan'),
        ('al', 'Albania'),
        ('dz', 'Algeria'),
        ('ad', 'Andorra'),
        ('ao', 'Angola'),
        ('ag', 'Antigua and Barbuda'),
        ('ar', 'Argentina'),
        ('am', 'Armenia'),
        ('au', 'Australia'),
        ('at', 'Austria'),
        ('az', 'Azerbaijan'),
        ('bs', 'Bahamas'),
        ('bh', 'Bahrain'),
        ('bd', 'Bangladesh'),
        ('bb', 'Barbados'),
        ('by', 'Belarus'),
        ('be', 'Belgium'),
        ('bz', 'Belize'),
        ('bj', 'Benin'),
        ('bt', 'Bhutan'),
        ('bo', 'Bolivia'),
        ('ba', 'Bosnia and Herzegovina'),
        ('bw', 'Botswana'),
        ('br', 'Brazil'),
        ('bn', 'Brunei'),
        ('bg', 'Bulgaria'),
        ('bf', 'Burkina Faso'),
        ('bi', 'Burundi'),
        ('cv', 'Cabo Verde'),
        ('kh', 'Cambodia'),
        ('cm', 'Cameroon'),
        ('ca', 'Canada'),
        ('cf', 'Central African Republic'),
        ('td', 'Chad'),
        ('cl', 'Chile'),
        ('cn', 'China'),
        ('co', 'Colombia'),
        ('km', 'Comoros'),
        ('cd', 'Democratic Republic of the Congo'),
        ('cg', 'Republic of the Congo'),
        ('cr', 'Costa Rica'),
        ('hr', 'Croatia'),
        ('cu', 'Cuba'),
        ('cy', 'Cyprus'),
        ('cz', 'Czech Republic'),
        ('dk', 'Denmark'),
        ('dj', 'Djibouti'),
        ('dm', 'Dominica'),
        ('do', 'Dominican Republic'),
        ('ec', 'Ecuador'),
        ('eg', 'Egypt'),
        ('sv', 'El Salvador'),
        ('gq', 'Equatorial Guinea'),
        ('er', 'Eritrea'),
        ('ee', 'Estonia'),
        ('et', 'Ethiopia'),
        ('fj', 'Fiji'),
        ('fi', 'Finland'),
        ('fr', 'France'),
        ('ga', 'Gabon'),
        ('gm', 'Gambia'),
        ('ge', 'Georgia'),
        ('de', 'Germany'),
        ('gh', 'Ghana'),
        ('gr', 'Greece'),
        ('gd', 'Grenada'),
        ('gt', 'Guatemala'),
        ('gn', 'Guinea'),
        ('gw', 'Guinea-Bissau'),
        ('gy', 'Guyana'),
        ('ht', 'Haiti'),
        ('hn', 'Honduras'),
        ('hu', 'Hungary'),
        ('is', 'Iceland'),
        ('in', 'India'),
        ('id', 'Indonesia'),
        ('ir', 'Iran'),
        ('iq', 'Iraq'),
        ('ie', 'Ireland'),
        ('il', 'Israel'),
        ('it', 'Italy'),
        ('jm', 'Jamaica'),
        ('jp', 'Japan'),
        ('jo', 'Jordan'),
        ('kz', 'Kazakhstan'),
        ('ke', 'Kenya'),
        ('ki', 'Kiribati'),
        ('kp', 'North Korea'),
        ('kr', 'South Korea'),
        ('kw', 'Kuwait'),
        ('kg', 'Kyrgyzstan'),
        ('la', 'Laos'),
        ('lv', 'Latvia'),
        ('lb', 'Lebanon'),
        ('ls', 'Lesotho'),
        ('lr', 'Liberia'),
        ('ly', 'Libya'),
        ('li', 'Liechtenstein'),
        ('lt', 'Lithuania'),
        ('lu', 'Luxembourg'),
        ('mk', 'North Macedonia'),
        ('mg', 'Madagascar'),
        ('mw', 'Malawi'),
        ('my', 'Malaysia'),
        ('mv', 'Maldives'),
        ('ml', 'Mali'),
        ('mt', 'Malta'),
        ('mh', 'Marshall Islands'),
        ('mr', 'Mauritania'),
        ('mu', 'Mauritius'),
        ('mx', 'Mexico'),
        ('fm', 'Micronesia'),
        ('md', 'Moldova'),
        ('mc', 'Monaco'),
        ('mn', 'Mongolia'),
        ('me', 'Montenegro'),
        ('ma', 'Morocco'),
        ('mz', 'Mozambique'),
        ('mm', 'Myanmar'),
        ('na', 'Namibia'),
        ('nr', 'Nauru'),
        ('np', 'Nepal'),
        ('nl', 'Netherlands'),
        ('nz', 'New Zealand'),
        ('ni', 'Nicaragua'),
        ('ne', 'Niger'),
        ('ng', 'Nigeria'),
        ('no', 'Norway'),
        ('om', 'Oman'),
        ('pk', 'Pakistan'),
        ('pw', 'Palau'),
        ('pa', 'Panama'),
        ('pg', 'Papua New Guinea'),
        ('py', 'Paraguay'),
        ('pe', 'Peru'),
        ('ph', 'Philippines'),
        ('pl', 'Poland'),
        ('pt', 'Portugal'),
        ('qa', 'Qatar'),
        ('ro', 'Romania'),
        ('ru', 'Russia'),
        ('rw', 'Rwanda'),
        ('kn', 'Saint Kitts and Nevis'),
        ('lc', 'Saint Lucia'),
        ('vc', 'Saint Vincent and the Grenadines'),
        ('ws', 'Samoa'),
        ('sm', 'San Marino'),
        ('st', 'Sao Tome and Principe'),
        ('sa', 'Saudi Arabia'),
        ('sn', 'Senegal'),
        ('rs', 'Serbia'),
        ('sc', 'Seychelles'),
        ('sl', 'Sierra Leone'),
        ('sg', 'Singapore'),
        ('sk', 'Slovakia'),
        ('si', 'Slovenia'),
        ('sb', 'Solomon Islands'),
        ('so', 'Somalia'),
        ('za', 'South Africa'),
    ]

    COUNTRIES_DICT = dict(COUNTRIES_LIST)
    
    country = forms.ChoiceField(
        choices=COUNTRIES_LIST,
        widget=forms.Select(attrs={'class': 'dropdown-class'}),
        label='Where are you from? (optional)',
        required=False
    )

    form_points = forms.CharField(widget=forms.HiddenInput(), required=False)
    form_zombie_deaths = forms.CharField(widget=forms.HiddenInput(), required=False)
    form_time_elapsed = forms.CharField(widget=forms.HiddenInput(), required=False)
    form_rank = forms.CharField(widget=forms.HiddenInput(), required=False)

    email = forms.EmailField(widget=forms.HiddenInput(), required=False)