services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - sqlite_data:/data
      - media_data:/app/media
      - assets_data:/assets
volumes:
  sqlite_data:
  media_data:
  assets_data: