services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - path: .env
        required: false
    restart: always
