# Generated by Django 4.1.4 on 2023-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, default=None)),
                ('name', models.TextField(blank=True, default=None)),
                ('message', models.TextField(blank=True, default=None)),
                ('subject', models.TextField(blank=True, default=None)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ignore_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
        ),
    ]
