# Generated by Django 4.1.4 on 2023-01-30 12:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.main_image_path),
        ),
    ]
