# Generated by Django 4.1.4 on 2023-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='country_full',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='country_short',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
