# Generated by Django 4.1.4 on 2023-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_leaderboard_country_full_leaderboard_country_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='zombie_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
