# Generated by Django 4.1.4 on 2023-01-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('project_acronym', models.CharField(default=None, max_length=3)),
                ('description', models.TextField(default=None)),
                ('additional_description', models.TextField(default=None)),
                ('technology', models.CharField(default=None, max_length=20)),
                ('image', models.FilePathField(path='/portfolio')),
                ('blog', models.TextField(default=None)),
                ('produced_at', models.TextField(default=None)),
                ('youtube_link', models.TextField(default=None)),
                ('youtube_embed', models.TextField(default=None)),
                ('tag', models.TextField(default=None)),
            ],
        ),
    ]
