# Generated by Django 4.1.4 on 2023-04-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_clips_video_alter_projects_image_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
