# Generated by Django 4.1.4 on 2023-04-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='created_at',
            new_name='project_date',
        ),
    ]
