# Generated by Django 4.1.4 on 2023-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_created_at_projects_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
