# Generated by Django 4.1.4 on 2023-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
