# Generated by Django 4.1.4 on 2023-06-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('software_used', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('task_type', models.CharField(blank=True, max_length=100, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('path_to_capture', models.CharField(blank=True, max_length=500, null=True)),
                ('path_to_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('studio_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='upvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='dailies.capture')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture', to='dailies.capture')),
            ],
        ),
        migrations.AddField(
            model_name='capture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='dailies.project'),
        ),
    ]
