# Generated by Django 4.1.4 on 2023-06-14 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='upvotes',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
