# Generated by Django 4.1.4 on 2023-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0002_comments_uuid_upvotes_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
