# Generated by Django 4.1.4 on 2023-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0002_capture_comments_project_upvotes_delete_dailies_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='path_to_capture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
