# Generated by Django 4.1.4 on 2023-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0003_project_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
