# Generated by Django 4.1.4 on 2023-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0004_capture_path_to_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='path_to_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
