# Generated by Django 4.1.4 on 2023-07-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0004_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
