# Generated by Django 4.1.4 on 2023-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0005_alter_capture_path_to_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
