# Generated by Django 4.1.4 on 2023-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0007_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capture',
            name='path_to_capture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
