# Generated by Django 4.1.4 on 2023-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0008_capture_comments_count_alter_capture_path_to_capture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotes',
            name='user',
        ),
        migrations.AddField(
            model_name='upvotes',
            name='user_ip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
