# Generated by Django 4.1.4 on 2023-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0011_comments_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
