# Generated by Django 4.1.4 on 2023-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0012_capture_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='media_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
