# Generated by Django 4.1.4 on 2023-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0013_capture_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='software_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
